### ISSUE TITLE
Input and output policy format issue

### ISSUE THREAD

**Issue by n13eho** [microsoft/RL4BandwidthEstimationChallenge#5]
Hi there, i'm figuring out the valid input and output of onnx model, and i noticed that there are torch_policy.py and run_baseline_model.py that **standardized input and output**. 
However, when i try to replace the path of `onnx_modelin` in run_baseline_model.py to `./tmp/onnxBwModel.onnx` which is the dummy onnx model output of torch_policy.py, the input difference occurs and failed the run_baseline_model.py. Here's the error message:

```bash
Traceback (most recent call last):
  File "/workspace/RL4BandwidthEstimationChallenge/run_baseline_model.py", line 39, in <module>
    bw_prediction, hidden_state, cell_state = ort_session.run(None, feed_dict)
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: obs Got: 2 Expected: 3 Please fix either the inputs or the model.
```

As you can notice, *Invalid rank for input: obs Got: 2 Expected: 3 Please fix either the inputs or the model*. It means the input of dummy onnx model requires `obs` of 3-dims, which is different from the baseline model. So which is the very valid input and output format, should i strictlly follow the format in run_baseline_model.py?

**Comment by skhairy0** [comment]
Hi @n13eho, thank you for raising my attention to this matter. I have updated run_baseline_model.py as well as the baseline model /onnx_models/Offline_RL_baseline_bandwidth_estimator_model.onnx in my last push to be consistent with the required input/output shapes in tf_policy.py and torch_policy.py. Please check and let me know if you have any further concerns!
