### ISSUE TITLE
Why are there such long audio-only frames in the early stages of trace？

### ISSUE THREAD

**Issue by qiansize** [microsoft/RL4BandwidthEstimationChallenge#8]
In the dataset, almost 200 MIs scores from the early stages of a trace are audio-only, which means that about the first 10 seconds of the call are audio only. Is this normal, or is the actual MI in the detection phase shorter than 60ms?

**Comment by skhairy0** [comment]
Hi @qiansize, that is right. The first 10~15 seconds only carry audio traffic as video transmission starts later. During this period, video quality score is not defined as mentioned [here](https://www.microsoft.com/en-us/research/academic-program/bandwidth-estimation-challenge/tips/#:~:text=People-,Objective%20Metrics,-In%20our%20audio).
